alias ls='ls -G'
alias ll='ls -alG'
alias whereami='pwd'
alias df='df -H'

### Added by the Heroku Toolbelt
### export PATH="/usr/local/heroku/bin:$PATH"

### Added by HomeBrew
export PATH=/usr/local/share/npm/bin/:/usr/local/sbin:/usr/local/heroku/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin

source ~/.git-prompt.sh

PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '

# The next line updates PATH for the Google Cloud SDK.
export PATH=/usr/local/google/google-cloud-sdk/bin:$PATH
